
project_id = "kiuaitdfimlmgvkybuxx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions.fetch-menopause-research]
verify_jwt = false

[functions.enhanced-content-fetch]
verify_jwt = false

[functions.daily-quote]
verify_jwt = false

[functions.suggest-wellness-goals]
verify_jwt = false

[functions.test-api-connectivity]
verify_jwt = false
